excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- Frameworks
- Source/ExcludedFolder
- Source/ExcludedFile.swift

cyclomatic_complexity: 12
file_length: 550
function_body_length: 80
function_parameter_count: 8
line_length: 200
type_body_length: 300
variable_name:
min_length:
error: 1
warning: 1

opt_in_rules:
- force_unwrapping

disabled_rules:
- valid_docs
- trailing_whitespace
- nesting
- type_name
- identifier_name

custom_rules:
smiley_face:
name: "Smiley Face"
regex: '( :\))'
match_kinds:
- comment
- string
message: "A closing parenthesis smiley :) creates a half-hearted smile, and thus is not preferred. Use :]"
severity: warning
